### ISSUE TITLE
Set X-Amz-Date for browser caching

### ISSUE THREAD

**Issue by seanpascoe** [sorentwo/carrierwave-aws#135]
Carrierwave-aws was a breeze to setup. Everything is working great except browser caching--the same images are fetched from s3 every time because the query string parameters change with every render. I was comparing the parameters and it looks like the "X-Amz-Date" param is just the current time, to the second. I was thinking of changing that date to zero for hour, minute, second, and that would keep the url the same, and allow browser caching for the current day. Is there anyway to overwrite this "X-Amz-Date" param? Thanks

**Comment by sorentwo** [comment]
A new URL will be generated every time you call the `url` method, no matter how you configure aws-sdk-s3. You can cache the page or response containing the url by using etags or last-modified headers for the parent object. Otherwise you can cache individual urls using the Rails cache.

However you approach caching, the `X-Amz-Date` param will change every time (and is part of how the url is signed). You can't change that.
