### ISSUE TITLE
Minimal rights policy ?

### ISSUE THREAD

**Issue by guizmaii** [sorentwo/carrierwave-aws#41]
Hi,

What's the minimum rights policy should I give to my AWS user in order to use your gem ?
Maybe, you should document that specific point in your README. I will not give full access to my S3 buckets, and secrity aware people would do the same.

Regards,
Jules

**Comment by sorentwo** [comment]
There isn't any minimum ACL policy that you need to use. Read, write, read ACL and write ACL policies all work equally well with the correct credentials. Also, an authenticated URL will be generated for any private object that requires credentials for viewing. You are welcome to keep everything private in your buckets, I store millions of private objects perfectly fine!

If you are referring to IAM policies that is entirely separate and shouldn't have any effect on using carrierwave-aws.

**Comment by guizmaii** [comment]
I'm talking about IAM policies. 
I'm not agree that it doesn't have effect on using your gem because if I want to give the minimum rights to my Amazon user I should know what your gem want to do in my bucket.

After some tries, we are not able to determine which rights your gem needs.
We tried to allow only s3:GetObject and s3:PutObject but it's not sufficient, I get an "unauthorized access error" and I don't understand why, we only put data ! 
If I only put data why s3:PutObject, is not sufficient ? 
I wrote an other app where I use the aws-sdk gem directly, I gave only the s3:PutObject write because I only put data (like in the app that use your gem) and it's work very well.

So what minimal rights should I give to my user ? And why s3:PutObject is not sufficient ?

**Comment by sorentwo** [comment]
The gem uses shortcuts for most operations. For example, rather than `get_object` it uses `objects[]`, so that may be causing your issues.

Every operation performed through `aws` can be found in [aws_file.rb](https://github.com/sorentwo/carrierwave-aws/blob/master/lib/carrierwave/storage/aws_file.rb). Overall the operations performed are:

* object read ([path])
* object deletion (delete)
* object creation (write)
* object url generation (url_for)
* object copy (copy_to)
