### ISSUE TITLE
aws file link

### ISSUE THREAD

**Issue by anklos** [sorentwo/carrierwave-aws#63]
Hi there,

I am generating some reports in my project, which needs to have links to point to the pdf files uploaded to the s3.

As the aws credentials I am using will expire the file link after a while(which means I cannot use those static links in the report), so I wonder is there any simple set up could support this:

1. in the report, file hypelink behind looks like `www.example/documents/1`
2. when user clicks the link, it goes to my server authentication.
3. if server authentication passes, rails server will create a aws file link, like `https://xxx.s3-ap-southeast-1.amazonaws.com/uploads/xxx/xxx/3/xxx.jpeg?AWSAccessKeyId=xxxxx&Expires=xxx&Signature=xxxxx`

Thanks!

**Comment by sorentwo** [comment]
@anklos: That sounds like a good plan. I've seen others use a similar scheme for processing thumbnails or previews on the fly, rather than automatically on save.

I don't know of any automatic "simple" way to do what you're asking. You can definitely configure an endpoint that will look up a model based on the path, generate an authenticated URL and then respond just with the URL. I'd suggest caching the results on the server as pre-signing authenticated URLs can be a slow process, you wouldn't want to re-sign every time an image is looked up.
