### ISSUE TITLE
Getting Error "The bucket you are attempting to access must be addressed using the specified endpoint." 

### ISSUE THREAD

**Issue by JMKelley** [sorentwo/carrierwave-aws#68]
Hi there,

Im consistently getting this error:

'The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.'

when using your gem alongside carrier wave on my localhost.

I have a stackoverflow link here with details explaining this issue in full.

http://stackoverflow.com/questions/32619941/s3-carrierwave

Thanks

**Comment by sorentwo** [comment]
I took a look at your question on stack overflow and answered there, but I'll duplicate it here as well.

It looks like you have set up an incorrect asset host. Remove that configuration and see if that clears up the problem.

**Comment by flanger001** [comment]
Apologies for posting on an old thread, but I was running into the same issue. This error is easier to debug if you can figure out what URL you're actually generating. In my case it was of the form https://[BUCKET_NAME].s3-[REGION].amazonaws.com/, so I just manually browsed to that URL and got a very helpful response:

```xml
<Error>
  <Code>PermanentRedirect</Code>
  <Message>
    The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
  </Message>
  <Bucket>[BUCKET_NAME]</Bucket>
  <Endpoint>s3.amazonaws.com</Endpoint> <!-- this is the correct endpoint -->
  <!-- extra stuff omitted -->
</Error>
```

It was because I was using the wrong *REGION*. I used this chart to figure out what region I should be using based on that endpoint, and everything started working again: http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

Here's my `config/initializers/carrierwave.rb` file for the interested, it's about as minimal a config as you can get:

```ruby
CarrierWave.configure do |config|
  config.storage = :aws
  config.aws_bucket = ENV['AWS_BUCKET_NAME']
  config.aws_acl = ENV['AWS_BUCKET_ACL']

  config.aws_attributes = {
    cache_control: "max-age=#{365.day.to_i}",
  }

  config.aws_credentials = {
    access_key_id: ENV['AWS_ACCESS_KEY_ID'],
    secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
    region: ENV['AWS_BUCKET_REGION'],
  }

  config.cache_dir = "#{Rails.root}/tmp/uploads"
end
```
