### ISSUE TITLE
Can't upload files larger than 5GB

### ISSUE THREAD

**Issue by guss77** [sorentwo/carrierwave-aws#83]
When trying to upload files that are larger than 5GB, we are getting an exception: `Aws::S3::Errors::EntityTooLarge: Your proposed upload exceeds the maximum allowed size`

It looks like that until AWS SDK v1, where `AWS::S3::S3Object.write` handles large files by automatically switching to multi-part upload (http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadInitiate.html), in AWS SDK v2 you either have to implement that same functionality yourself using `Aws::S3::Client.create_multipart_upload` (and friends), or use the file base `Aws::S3::Object.upload_file` that also implements multi-part automatically.

**Comment by sorentwo** [comment]
@guss77 I have to admit, I haven't encountered uploads larger than 5GB for any carrier-wave usage. I'm happy to review and help with a PR, but it isn't something I have time to work on currently.

**Comment by guss77** [comment]
We use carrierwave to upload large video files - videos larger than 5GB are rare, but they do happen.

I'd like to also point out that AWS SDK v1 default size to trigger multi-part upload is 16MB - so it stands to reason that there are some performance benefits to using multi-part uploads even if you don't get into the >GB file sizes.

I would be happy to provide a PR to solve this, but why did you close the ticket? Its quite uncommon for a maintainer to close a ticket just for the reason that they specifically have no time to work on the fix. The normal behavior is to keep it open so that someone else might pick it up and fix it - the power of Open Source Software and such.

**Comment by guss77** [comment]
Looking at the code, the solution is probably as simple as changing `aws_file.rb` `store()` to use `S3::Object#upload_file` instead of `S3::Object#upload_file`, which already has automatic multi-part support - but that call only takes a path to a file on the file system. 

I'm not sure what data `store()` receives, but if it can't be normalized to a file path, then the `store()` has to be modified to detect the actual upload size and either use standard `#put` for small files and in case of large files call `#initiate_multipart_upload` (and friends) and chunk the data itself.

**Comment by sorentwo** [comment]
@guss77 I closed the ticket because I see this as a feature request, not a bug fix. My focus (and responsibility) is maintaining the project, but my time for feature additions is very limited. I understand it is important for your use case, which is why I encourage you to open a PR for it.

The `store` method receives data from carrierwave itself, it should always be a file like object, but not necessarily a file that has a path.

**Comment by guss77** [comment]
A. You could have said that you'd want this to be reported as a "feature" instead of a "bug" while closing - that would have made seem a rather different approach then what I heard initially, which was something like "I don't have time for your problem - closed."
B. I'm not sure how to create a "feature request" vs. a "bug fix" - the Github UI only has "new issue" and I don't have access to setting labels/milestones (if such exist for the project). If you have some instructions for opening feature requests, please let me know.
C. We are working no a PR (my previous comment was mostly instructions for the developer who is going to tackle this - and thanks for your clarification!), expect to see one soon.

**Comment by sorentwo** [comment]
A. Fair enough, I'll try to be more clear about this in the future.
B. Several of the projects I have maintained or contributed to (mperham/inspeqtor, elixir-lang/ecto) have the same policy about issues requesting a feature. There isn't a different way to make a feature request, I just ask that those interested in a feature open a PR for it because new features in this project aren't a priority for me.
C. Awesome that you're working on a PR, I look forward to seeing the solution.
