### ISSUE TITLE
Support for Synchronising Assets between Rails and S3

### ISSUE THREAD

**Issue by Tenzil** [sorentwo/carrierwave-aws#91]
Hi All,
Thank you all for this wonder stuff. 
Do you guys provide support for Synchronising Assets between Rails and S3
Once again thanks

**Comment by sorentwo** [comment]
This library is only an adapter for CarrierWave, it can't be used on its own at all. CarrierWave doesn't provide support for that kind of work, but you could achieve it using [aws-sdk](https://github.com/aws/aws-sdk-ruby) directly. However, I'd really recommend fronting your application with a CDN instead of pre-uploading assets on every deploy.
