### ISSUE TITLE
AWS::S3::Errors::RequestTimeTooSkewed

### ISSUE THREAD

**Issue by NotYourAverageDeveloper** [sorentwo/carrierwave-aws#96]
After switching from fog to carrierwave-aws, I am recieving this error

`The difference between the request time and the current time is too large.`

I've fixed this problem when I was using fog with this line of code

`Fog::Storage.new(config.fog_credentials).sync_clock`

Is there an alternative for this using carrierwave-aws.

Thanks.

**Comment by sorentwo** [comment]
As far as I can tell there isn't anything built into aws-sdk that handles clock drift. The `sync_clock` method from fog is [updating an internal Time class](https://github.com/fog/fog/blob/9640e77d29e07b3d6de576cba46bc6e4294debf6/lib/fog/internet_archive/requests/storage/sync_clock.rb#L7) to alleviate the problem. Fog can get away with that because it is making connections to s3 itself, but carrierwave-aws can't, because we're using aws-sdk.

This isn't something you should be encountering, especially not on a regular basis. The best thing to do is be sure that your server (or local machine) has its clock in sync with a time server.

If you're unable to get the time to sync your best bet is to open an issue with aws-sdk.
